### ISSUE TITLE
[beginners/list] Příklad u PyLadies na seznamy není dobrý 

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#102]
Vůbec se netýká seznamů a jde dělat čistě nad řetězci. Navíc ta historka o tahu počítače, co umí hrát  jen za křížky je taková... ehm, radši opravit než dělat 2 konverze.

**Comment by encukou** [comment]
+1, chce to jiný příklad

Ale tah počítače co umí hrát jen za křížky je překvapivě častý :)

**Comment by hroncok** [comment]
> Ale tah počítače co umí hrát jen za křížky je překvapivě častý :)

Ano, ale nabádat je k „opravě“ tohoto špatného návrhu tímto způsobem není podle mě dobré. I když zde to slouží jako záminka, někdo by mohl mít pocit, že takto by se to mělo dělat.

**Comment by encukou** [comment]
Opraveno v https://github.com/pyvec/naucse.python.cz/pull/104
