### ISSUE TITLE
Spolupráce a OSS

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/naucse.python.cz#14]
Tato lekce potřebuje nějaký nový způsob, jak čtenáři mohou testovat spolupráci v gitu, potože část pro kouče bude smazána a tím pádem nedává testování s prezenční listinou do budoucna smysl. Leda bychom udělali nějaký automaticky udržovaný repozitář, který by se v pravidelných intervalech mazal.

Nebo nějaké repo, které budeme všichni sledovat a čtenáři, který pošle PR ho prostě mergneme. Když jej budeme sledovat všichni, tak toho snad nebude tolik.

To jsou však jen rychlé nápady.

**Comment by encukou** [comment]
Moje repo s prezenčkou je stále k dispozici; mažu ho vždycky před lekcí kterou učím já. Takže by to mělo fungovat tak, jak je to tam napsáno.

Taky je možnost udělat novou prezenčku pod účtem pyvec, ale nemyslím že je to moc akutní.

**Comment by frenzymadness** [comment]
Jen jsem nad tím přemýšlel jako nad materiály pro všechny a ne jen pro PyLadies, takže mě napadlo, že to budeme muset do budoucna nějak vyřešit.

Akutní to zcela jistě není.

**Comment by encukou** [comment]
Po zkušenostech z TestLadies Sandbox repem, které bylo pod Pyvcem a tudíž ho naše nástroje braly jako projekt Pyvce, bych to rád nechal tak, jak to je. Na kurzu ať repo udělá hlavní kouč pod svým účtem, lidi bez kurzu ať to posílají ke mě.
