### ISSUE TITLE
I do no longer see Travis CI integration here

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#148]
The Travis CI builds are running, but I don't see the results next to PRs, commits, etc.

Is it just me?

**Comment by encukou** [comment]
Me too. No idea how this came to be, though :(

**Comment by hroncok** [comment]
@encukou Could you plese try disabling and enabling this repo in Travis?

![ofandon](https://user-images.githubusercontent.com/2401856/27081382-66978d3c-5040-11e7-9250-71e4b2796703.jpg)

**Comment by encukou** [comment]
Probably an authorization issue. Turning several things off and on and some overuse the Sync button made `pyvec` appear in Travis so I could turn this repo's integration off and on. Let's see if that unclogs the pipes!
Note to self – This may be relevant: https://github.com/travis-ci/travis-ci/issues/2519

**Comment by hroncok** [comment]
Seems to work again. Thanks.

**Comment by encukou** [comment]
Thank you for noticing!

**Comment by hroncok** [comment]
Took me a month to notice :)
