### ISSUE TITLE
Inconsistency in runs/ URLs

### ISSUE THREAD

**Issue by Sanqui** [pyvec/naucse.python.cz#156]
* http://naucse.python.cz/runs/
* http://naucse.python.cz/2017/pyknihovny-brno/
* http://naucse.python.cz/runs/2017/pyknihovny-brno/sessions/requests-click/ <- should not start with runs/.
* http://naucse.python.cz/2017/pyknihovny-brno/fast-track/install/

**Comment by encukou** [comment]
I missed the coverpage URL in the review. Sorry for that!

This needs redirect on the old URLs, so we don't break potential links.
If you work on this, please assign yourself to prevent duplicate URLs (@Krejdom, @Sanqui).
