### ISSUE TITLE
MI-PYT MicroPython: Add ampy

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#162]
https://github.com/adafruit/ampy

**Comment by hroncok** [comment]
@encukou The flip of lessons makes this higher priority. I'm assigned and will eventually do it, but if you'll go trough the materials anyway, please, add ampy while doing that.

**Comment by encukou** [comment]
Most likely I'll only get to this on Tuesday.

**Comment by hroncok** [comment]
That would be the case for me as well.

**Comment by hroncok** [comment]
On it.
