### ISSUE TITLE
Rename sessions/ to chapters/ or drop it entirely

### ISSUE THREAD

**Issue by Sanqui** [pyvec/naucse.python.cz#164]
"Sessions" is the name used for cover pages, but it makes less sense in the context of online materials.  In reality, they're closer to chapters.

Česky se na té stránce píše "lekce".

e.g. http://naucse.python.cz/2017/pyknihovny-brno/sessions/requests-click/

**Comment by encukou** [comment]
Yes, the terminology for hybrid online/offline courses isn't straightforward. If you come up with something that's better for both, please change it (assuming URLs stay working).

**Comment by encukou** [comment]
We couldn't find a better term. It is `sessions`.
