### ISSUE TITLE
Odkazy na úkoly MI-PYT se budou měnit

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#170]
Pokud zůstanou zde současné linky, rozbijou se. Řešením je v běhu pyknihovny Brno změnit linky na branch b161, případně si vytvořit vlastní branch pyknihovny2017 nebo tak něco. Linky na úkoly v samotném textu bych odstranil a nechal jen v bězích.

**Comment by encukou** [comment]
Úkoly jsme používali z b161, zpětně dělat pyknihovny2017 nemá smysl.
