### ISSUE TITLE
Piskvorky chybí

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/naucse.python.cz#18]
Z dopisů uživatelů:

> Cus, neviem kto presne z vas ma nastarosti ten nauce.python.cz tak pisem obom, ze som nasiel bug :)
> http://naucse.python.cz/courses/testing/ (odvolava sa tam na nejaky piskvorky modul, kt predpokladam presli ludia na pyladies, ale nie je to nikde predtym v materialoch..)

@kvbik:

> Primo to nemame na starosti ani jeden, ale info predame dal. Nejlepsi je nahlasit issue na githubu.
> Jsem trosku v rozpacich, zda nejsou v lepsim stavu materialy pyladies. Naucse je mozna porad trochu WIP. 

Odpověď:

> Aha! Tak v tom pripade este odporucam predat dalsie info dalej nech sa prida na nauce.python.cz aj link na git repo :)

**Comment by encukou** [comment]
No jo, naucse je teď hodně WIP :(
Jak se o tom lidi dozvěděli? Já jsem to doufám moc nepropagoval

**Comment by honzajavorek** [comment]
Myslím, že @lspdv trochu rozhazovala sítě, ale tak najdeš to i přes Google 😉

**Comment by honzajavorek** [comment]
Možná by se hodilo udělat nahoře nějaký upozoňující pásek, který vysvětlí, že je to WIP, bude tam link na aktuální PyLadies materiály a link na GitHub repo.

**Comment by encukou** [comment]
@krejdom, dáš nahoru na každou stránku vysvětlující pásek, že na tom makáš? :)

**Comment by lspdv** [comment]
No toto vzniklo tak, ze jsme se o tom bavili na porade a pak se to zaclo
prosazovat stylem - Ucastnici na Pyworkingu by mli mit projete materialy
pyladies.cz nebo naucse.python.cz

Nemam info o tom, ze tam jsou stale stare materialy.
Me posleni info bylo, ze na tom dela Domca na stazi a ze jde o frontendove
upravy.

:-)

To se moc omlouvame.

@krejdom - dej tam pasek jak pisou kluci a pripis tam info, ze to dodelavas
ty jako stazistka a byvala PyLady. to bude cool :-)) Lidi zase budou o neco
vic presvedceni, ze ma cenu hledat si open source projekty na rozvijeni se
:-)

Dne 14. prosince 2016 17:07 Petr Viktorin <notifications@github.com>
napsal(a):

**Comment by honzajavorek** [comment]
Pasek uz tam je - #19
