### ISSUE TITLE
Python 3.6 f-strings

### ISSUE THREAD

**Issue by Aprillion** [pyvec/naucse.python.cz#180]
Chceme zjednodusit kapitolu o string formatting a pouzit `f'string {interpolation}'` namiesto `.format()`? Tym padom by ale bola min. pozadovana verzia pythonu 3.6...

**Comment by encukou** [comment]
Chceme, jen nevím jestli teď.
Asi bych počkal jestli někdo na kurzu bude mít starší Python.

**Comment by hroncok** [comment]
Uděláme na PyLadies průzkum nainstalovaných verzí?

**Comment by messa** [comment]
Počkejte aspoň až bude 3.6 v Debianu stable a v Ubuntu LTS. Účastnice Pyladies co si Python instalovaly do Windows si instalovaly rovnou 3.6.2, ale třeba v Ubuntu bych si nebyl jistý, co kdo má, resp. co si může relativně snadno nainstalovat.

A taky tím neuděláme moc dobrou službu lidem, co po Pyladies půjdou něco dělat do reálných projektů, které tyhle latest featury ještě mít nebudou.

**Comment by encukou** [comment]
Reálné projekty bych tady zas tolik neřešil – někdo po začátečnickém kurzu přejde na Python 3.4, někdo na 2.7, někdo na 3.6 s [pycodestyle](https://pypi.python.org/pypi/pycodestyle/) a typovýma anotacema, někdo na C#. Rozdíly proti kurzu budou vždycky :)

Nastavit to podle Ubuntu LTS zní dobře. Podle [Ubunťáckého plánu](https://www.ubuntu.com/info/release-end-of-life) mi jako dobré datum k přechodu na 3.6 přijde druhá polovina 2018. Takže ještě dva PyLadies běhy s `format`.

**Comment by encukou** [comment]
Po tom, co formátování už znáš – ať už `format()` nebo `f""` – už podle mě není takový problém začít používat druhé, ale zmiňovat obě možnosti hned na začátku mi přijde že je jenom matoucí.

**Comment by frenzymadness** [comment]
Pokročilé formátování se vším, co k tomu patří, máme jako náplň Advanced Python kurzu.
