### ISSUE TITLE
V sekci "Probíhající kurzy" jsou již ukončené kurzy

### ISSUE THREAD

**Issue by mikicz** [pyvec/naucse.python.cz#197]
Oba dva kurzy v té sekci již kompletně proběhly. Momentálně probíhá jeden kurz pyladies v Praze, v Brně začnou další dva příští týden.

**Comment by encukou** [comment]
pozn. jde o hlavní stránku

**Comment by messa** [comment]
V Praze budou taky dva.

**Comment by hroncok** [comment]
poznámka: probíhající kurzy an hlavní stránce se negenerují samy, ale jsou zadrátované.
