### ISSUE TITLE
iCal for courses (runs)

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#200]
When I go to a specific run, such as http://naucse.python.cz/2017/mipyt-zima/

I'd like to see a (reasonably) big button that says: **add to my calendar** that links to an ical.

This should be fairly simple to implement, but would probably require to add times of starts and ends to the dates, or  globally to the run (possibly allowing both).

**Comment by messa** [comment]
BTW. similar to https://github.com/pyvec/pyworking.cz/issues/1

**Comment by encukou** [comment]
Oops, zapomněl jsem že je na tohle už issue.
Přidáno v https://github.com/pyvec/naucse.python.cz/pull/316, ale události se zatím ukazují se špatným časem, viz https://github.com/pyvec/naucse.python.cz/issues/317.
