### ISSUE TITLE
Sort runs at /runs/ by date of first session

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#203]
Currently, the runs are sorted by encukou-knows-what, probably slug. I think, it would be better, if the "latest" runs were on the top.

**Comment by mikicz** [comment]
You can sort the runs by creating `info.yml` in `runs/2017` with the order (see `courses/info.yml`). You can also just add the order of the first couple you want to sort and the rest will be sorted by the slug alphabetically

**Comment by hroncok** [comment]
Thanks. I still think the automatic sorting could be date based.
