### ISSUE TITLE
Odlišit příkaz a jeho výstup

### ISSUE THREAD

**Issue by messa** [pyvec/naucse.python.cz#222]
Feedback z kurzu. Nějak barevně. Mít na začátku příkazu znak `$` asi nestačí...

**Comment by encukou** [comment]
On ten výstup už je šedý, ale asi málo :)

Jak velký je to problém? Nevzpomínám si že bych tenhle feedback už viděl.

**Comment by messa** [comment]
Sdělil mi ho vedlejší kouč na [hodině gitu](http://naucse.python.cz/2017/pyladies-praha-podzim-cznic/git/git-collaboration-2in1/), tak jsem to sem zadal :) 

Teď koukám, že to je asi špatně implementované na té stránce - jsou to `<pre>` bloky bez jakéhokoliv syntax highlightingu, na rozdíl od předchozích lekcí.

**Comment by hroncok** [comment]
Je to špatně v tom zdroji. Používá se tam odsazení o 4 mezery místo ```console...
