### ISSUE TITLE
MI-PYT: Prohodit Pandas a NumPy

### ISSUE THREAD

**Issue by encukou** [pyvec/naucse.python.cz#237]
Lekce o Pandas je dlouhá, o NumPy kratší. Bylo by asi lepší je prohodit a společné věci přesunout k NumPy, aby se to vyvážilo.

**Comment by encukou** [comment]
Tohle by mělo pomoct s https://github.com/pyvec/naucse.python.cz/issues/234

**Comment by hroncok** [comment]
Případně můžeme (třeba dočasně) společnou část mít u obou, ale napsat tam „tohle se dělá stejně jako v NumPy/Pandas, pokud to již umíte, můžete přeskočit na sekci XYZ.“ To nám umožní to udělat (a mergnout) ještě před koncem letošního MI-PYTu.
