### ISSUE TITLE
Malformed HTML in course overview

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#271]
http://naucse.python.cz/2017/pyladies-praha-podzim-ntk/ and others:

![_](https://user-images.githubusercontent.com/2401856/32740574-a6cf8888-c8a3-11e7-94f3-80b3ae0a6e03.png)

**Comment by encukou** [comment]
FWIW, this is caused by mistune 0.8 being stricter than 0.7.

**Comment by hroncok** [comment]
That explains https://github.com/pyvec/naucse.python.cz/pull/272#issuecomment-344228254
