### ISSUE TITLE
Měl by __init__ metatřídy volat super().__init__?

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#303]
Z materiálů o magie:

```python
class IterableMeta(type):
    def __init__(cls, name, bases, namespace):
        cls.items = sorted(n for n in namespace
                           if not n.startswith('__'))

    def __iter__(cls):
        return iter(cls.items)

class SimpleEnum(metaclass=IterableMeta):
    a = 1
    b = 2
    c = 3
    d = 4
```

Napadlo mě: neměl by `IterableMeta.__init__` volat `super().__init__(name, bases, namespace)`? Pokud to funguje bz něj, je to náhoda, nebo je to předpokládané chování? Dějí se věci, které vytvoří `SimpleEnum` jakožto třídu v konstruktoru a proto nevadí, že se nezavolá inicializátor?

**Comment by encukou** [comment]
Máš pravdu, je spíš náhoda, že `type.__init__` nadtřídy nic nedělá (všechno podstatné je v konstruktoru). U built-in typů to tak bývá, ale korektnější by bylo na to nespoléhat.
Opravíš to, prosím?

**Comment by hroncok** [comment]
ok
