### ISSUE TITLE
Matoucí označení složky ~/pyladies

### ISSUE THREAD

**Issue by Glutexo** [pyvec/naucse.python.cz#313]
Cesty v materiálech uvozené `~/pyladies`, např. `~/pyladies\venv\bin\activate` jsou pro začínající děvčata matoucí. Navíc když je podbarvené `~/pyladies` a lomítko za tím už ne, tak ty, co aspoň toto pochopí, tam stejně napíší to lomítko navíc.

Chtělo by to lepší řešení. Klidně něco primitivního, třeba `tvoje složka/venv\bin\activate` s podbarveným `tvoje složka/` včetně lomítka. Z toho by snad mohlo být docela jasné, že se to nemá přímo opisovat.

**Comment by Glutexo** [comment]
@frenzymadness a @encukou by k tomu možná mohli mít názor.

**Comment by frenzymadness** [comment]
Souhlasím, že by se to mohlo udělat jinak. Také jsem měl ten dojem včera, že to pojmenování není úplně šťastné a tilda na začátku tomu moc nepomáha.
Klidně něco jako `<tvoje_slozka>/` nebo tak něco.

**Comment by hroncok** [comment]
Zrovna ty zubaté závorky prosím ne. Pro nás to je jasné znamení, které
říká: nahradit opravdovou hodnotou. Ale pro začátečníky ne.

Dne 8. 2. 2018 3:44 odp. napsal uživatel "frenzymadness" <
notifications@github.com>:

**Comment by frenzymadness** [comment]
> Zrovna ty zubaté závorky prosím ne. Pro nás to je jasné znamení, které
> říká: nahradit opravdovou hodnotou. Ale pro začátečníky ne.

Tilda tam také je, i když začátečník netuší proč a co to znamená. Je třeba najít kompromis, který nebude profíkovi připadat hloupý a laik ho pochopí, i když třeba nebude znát jeho přesný význam.

**Comment by hroncok** [comment]
Já souhlasím, že tilda je matoucí. Jen jsem podotknul, že závorky taky.
Myslím si, že by to mělo být odlišeno primárně vizuálním stylem.

Dne 8. 2. 2018 3:59 odp. napsal uživatel "frenzymadness" <
notifications@github.com>:

**Comment by Glutexo** [comment]
Výraznější grafické oddělení by mohlo pomoct. Mělo by být jasné, že se jedná o zástupný symbol. Třeba nějak takhle: ![venv](https://user-images.githubusercontent.com/1161096/36014808-f1ba078a-0d6b-11e8-9ec7-285fed1630a1.png)

Důležité je, aby součástí toho podbarvení/oddělení bylo i to následující lomítko.

**Comment by hroncok** [comment]
Taky IMHO není dobré takhle kombinovat posixovou a windows cestu.

Dne 9. 2. 2018 7:37 dop. napsal uživatel "Štěpán Tomsa" <
notifications@github.com>:

**Comment by Glutexo** [comment]
* Mohou být dva styly, jeden pro Windows a jeden pro POSIX. Jen teda nevím, co tam dát na Windows místo vlnky, neboť tam nic takového neexistuje.
* Místo `~/pyladies/` může být cokoliv jiného. Tím, že je to podbarvené a oddělené tam ani nemusejí být žádné závorky.

Teď jak nad tím ale uvažuji, tak ona tam ta předpona snad ani nemusí být vůbec. Pokud by se nějak dostatečně zdůraznilo a připomínalo, že všechny cesty a příkazy jsou relativní k této složce.

**Comment by encukou** [comment]
S dvěma styly je problém – jak poznat který z nich ukázat?

To výraznější grafické zpracování by šlo; Glutexův návrh ![](https://user-images.githubusercontent.com/1161096/36014808-f1ba078a-0d6b-11e8-9ec7-285fed1630a1.png) se mi docela líbí.

**Comment by encukou** [comment]
Zkusím to celé obejít:
* Místo `~/pyladies` bude „adresář, kde máš soubory ke kurzům Pythonu“. Příklady jako `~/pyladies` a `C:\pyladies` budou jen v sekci o instalaci pro konkrétní systém.
* Cestu pak budou relativní, např.:
  * aktivace – „pomocí `cd` přejdi do adresáře, kde máš soubory ke kurzům Pythonu. Pak zadej `source __venv__/bin/activate`“
  * ukládání z editoru – „v adresáři, kde máš soubory ke kurzům Pythonu, si vytvoř nový adresář. Pojmenuj ho podle čísla této lekce.“

**Comment by Glutexo** [comment]
Ještě bych rád opravil své tvrzení, že pod Windows neexistuje nic jako `~`. Máme přece `%HOMEPATH%`! 🕺🏻
