### ISSUE TITLE
Domácí projekty PyLadies mají v nadpisech číslo 

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#359]
Což mate účastnice, pokud jsou lekce v jiném pořadí.

**Comment by encukou** [comment]
Viz https://github.com/pyvec/naucse.python.cz/issues/277
K tomu se asi hned tak nedostanu. Mezitím by se daly čísla nahradit názvama.

**Comment by encukou** [comment]
Už se nepoužívají.
