### ISSUE TITLE
Switch to HTTPS

### ISSUE THREAD

**Issue by encukou** [pyvec/naucse.python.cz#380]
GitHub generates a certificate for [some custom domains](https://github.com/isaacs/github/issues/156) – looks like a gradual rollout. And naucse is included!
When it's official, we need to switch all links to `naucse` to `https://`. (But not before – right now there's nothing preventing GitHub from reverting this.)

As for links to external pages, we can switch them now if the target supports `https`.

**Comment by hroncok** [comment]
Note that I suppose that if GitHub reverts it, it will probably revert the enforcing as well.

**Comment by encukou** [comment]
We need through the site and see if there's any more mixed content than [fonts](https://github.com/pyvec/naucse.python.cz/pull/379).
Unfortunately I don't have time for that right now. Can you either do it, or revert?

**Comment by hroncok** [comment]
Reverted for now

**Comment by hroncok** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=naucse.python.cz&latest

![naucsessl](https://user-images.githubusercontent.com/2401856/38504665-8dd56998-3c15-11e8-8842-5fb99602e5d6.png)

**Comment by hroncok** [comment]
https://www.jitbit.com/sslcheck/

Done. Total pages crawled: 200

Pages with unsecure content:
https://naucse.python.cz/course/mi-pyt/intro/async/ ?

```html
<img src="http://imgs.xkcd.com/comics/standards.png" alt="xkcd 927">
```

**Comment by hroncok** [comment]
Note that the jitbit.com/sslcheck is not reliable enough, as it should have have reported this problem on multiple pages.

**Comment by hroncok** [comment]
[mixed-content-scan](https://github.com/bramus/mixed-content-scan) scans 1729 pages and report several hundreds of errors and warnings, yet only the xkcd is something that is external everything else is controlled by us.

**Comment by hroncok** [comment]
Enforced HTTPS again, not changing any link.

**Comment by hroncok** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
