### ISSUE TITLE
Slovo navíc v první větě

### ISSUE THREAD

**Issue by barcza** [pyvec/naucse.python.cz#407]
ahoj, máte tam navíc jedno slovo :)
"tak malé, že se ho pohodlně schováš v ruce" - asi by tam nemělo být "se".
jen taková drobnost.

**Comment by hroncok** [comment]
Zvládneš poslat Pull Request? Jestli ne, nevadí, jen se ptám.

**Comment by barcza** [comment]
Minuly tyden jsme se to ucily, tak teoreticky bych mohla :-)
Mam? Akorat ted totalne nestiham. Snad o vikendu...

**Comment by hroncok** [comment]
Tak zkus. Do víkendu to určitě počká.

**Comment by barcza** [comment]
je možný, že se mi to povedlo :-) je to v pull requests pod číslem #408 
sorry, že mi to tak trvá a že to možná dělám zbytečně složitě...

**Comment by encukou** [comment]
V pohodě – časem ti to přejde do krve :)

**Comment by encukou** [comment]
Opraveno v #408
