### ISSUE TITLE
instalace MicroPythonu na NodeMcu

### ISSUE THREAD

**Issue by Kubiczek36** [pyvec/naucse.python.cz#414]
Dobrý den,
nedávno jsem si koupil Nodemcu z Aliexpressu [https://www.aliexpress.com/item/NodeMcu-Lua-WIFI-Internet-of-Things-development-board-based-ESP8266-module/32448461056.html?spm=a2g0s.9042311.0.0.302e4c4dBHsB75](url), a posléze se snažil na něj nainstalovat micropython tak abych ji mohl programovat.

Nejprve jsem se ji pokusil naprogramovat na mém počítači s Win10, podle návodu [https://naucse.python.cz/2018/micropython-workshop-ostrava/micropython/workshop-ostrava/](url) kde byl problém s ovladačem, který nefungoval.

Následně jsem podle stejného návodu pro Linux se pokusil ji zprovoznit na počítači s linuxem (Fedora násl. Lubuntu), kde u posledního kroku po stisknutí tlačítka `rst` na destičce se v příkazovím řádku objevila změť různých znaků a nešly zadávat žádné příkazy.

 Po neúspěchu jsem se pokusil (znovu na obou verzích linuxu) postupovat podle návodu https://naucse.python.cz/2017/rh-openschool-micropython/micropython/mini-workshop/organizers/, kde se mi nepovedlo naflashovat desku, příkaz `esptool.py --port /dev/ttyUSB0 erase_flash`' neustále házel chybu`Permision denied` ať jsem dělal co jsem dělal. 

Jak tedy mám správně postupovat, abych dosáhl toho že budu mít funkční destičku?

**Comment by encukou** [comment]
Jsi ve skupině dialout? Je to v [pokynech pro organizátory](https://naucse.python.cz/2017/rh-openschool-micropython/micropython/mini-workshop/organizers/), v sekci "Příprava počítače":
```console
$ sudo usermod -a -G dialout $(whoami)
$ su - $(whoami)
```

(Ten druhý příkaz je potřeba zadat znovu pro každou nově otevřenou konzoli, dokud nerestartuješ počítač.)

Jestli to nefunguje, poděl se prosím o celou chybovou hlášku, kterou dostáváš.

**Comment by Kubiczek36** [comment]
Ano měly bych být
`kuba@KubaPC:~/Dokumenty/nodemcu$ sudo usermod -a -G dialout $(whoami)

kuba@KubaPC:~/Dokumenty/nodemcu$ su - $(whoami)

Heslo: 

kuba@KubaPC:~$ groups

kuba adm dialout cdrom sudo dip plugdev lpadmin sambashare
`

**Comment by encukou** [comment]
A jakou chybu dostáváš?

**Comment by Kubiczek36** [comment]
Teď když se pokouším postupovat dál tak mi to píše tyto hlášky:
kuba@KubaPC:~$ python3 -m pip install --user adafruit-ampy
/usr/bin/python3: No module named pip
kuba@KubaPC:~$ sudo dnf install picocom ampy
sudo: dnf: příkaz nenalezen

**Comment by Kubiczek36** [comment]
Lubuntu

**Comment by hroncok** [comment]
Na Lubuntu není dnf. Doporučuju zkusit znovu Fedoru, tam umíme lépe poradit. Ale i na Lubuntu by to mělo nějak jít.

**Comment by Kubiczek36** [comment]
Dobrý, tak nakonec se mi to nějak podařilo zprovoznit. Moc děkuji za rady!

**Comment by hroncok** [comment]
A jak vlastně?

**Comment by encukou** [comment]
To už se asi nedozvíme :(
