### ISSUE TITLE
"Freeze" all old runs

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#419]
In order to make new changes safe, I porpose we freeze all runs by serving them from another branch.

My idea is to:

 1. create archived2017 branch and put all runs from 2017 in there
 2. create archived2018 branch and put all **past** runs from 2017 in there
 3. make the maintainers (@encukou, @vahalova?) to use forks for the current runs (for pyladies, preferably fork to @pyladiescz, I cannot do that)

Alternative would be to use separate forks for each run, but I don't think it's worth the effort.

I can proceed with 1 and 2.

**Comment by encukou** [comment]
The current run in Brno will end in a month, so we can add it to the archived2018 branch then, instead.

**Comment by hroncok** [comment]
Sure. If no changes are required.

**Comment by hroncok** [comment]
Can I proceed with 1 and 2?

**Comment by encukou** [comment]
Go ahead, please.
If the freezing API needs to change, we can touch the archived branches then.

**Comment by hroncok** [comment]
2017: https://github.com/pyvec/naucse.python.cz/pull/420

**Comment by hroncok** [comment]
Let's wait 10+ days and archive 2018 at once.

**Comment by encukou** [comment]
2019: https://github.com/pyvec/naucse.python.cz/pull/573
Issue for automation: https://github.com/pyvec/naucse.python.cz/issues/574
