### ISSUE TITLE
Errors in forks break non HTML pages

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#424]
When there is an error on a non-HTML page (such as ics), there is a HTML page rendered. That breaks FrozenFlask (expecting text/calendar by the filename, gets text/html).

![nauce_error](https://user-images.githubusercontent.com/2401856/42134622-d78ced48-7d3f-11e8-897f-5c183e5edd77.png)

No idea how we are supposed to handle this, but the current implementation breaks the entire build if this happens.

See https://github.com/pyvec/naucse.python.cz/pull/423#issuecomment-401604849 for context.

**Comment by hroncok** [comment]
For the calendar particularly this is being handled in https://github.com/pyvec/naucse.python.cz/blob/71cbde90cb71c0a11b45f5d7868ba8277e093843/naucse/views.py#L825-L834

We need to return something that has correct content type.

**Comment by encukou** [comment]
It's actually in the `.ics` route. https://github.com/pyvec/naucse.python.cz/blob/71cbde90cb71c0a11b45f5d7868ba8277e093843/naucse/views.py#L901-L910

To handle this in a static site we'd need an `iCal` error page. I don't think that's possible :(

**Comment by hroncok** [comment]
Right. Well, we can set the content type as a dirty workaround. The static site will then download an ics file with HTML content which isn't great, but at least it would build. Later, we can change the error to plaintext maybe.

**Comment by hroncok** [comment]
There's a power outage, so I'm on battery and cell data, so don't expect an actual fix/workaround from me any time soon.

**Comment by encukou** [comment]
ACK, I'll do the workaround.

**Comment by encukou** [comment]
> No idea how we are supposed to handle this, but the current implementation breaks the entire build if this happens.

Current implementation breaks the entire build if this happens, as do any errors.
The plan is that a course will show the last successful build; errors like this will prevent that one course from updating.
Also, dependencies for new courses are locked using pipenv.

See https://github.com/pyvec/naucse.python.cz/issues/494 for a high-level plan
