### ISSUE TITLE
Random

### ISSUE THREAD

**Issue by MartinJaks** [pyvec/naucse.python.cz#427]
Začal jsem jako samouk Pythonu a jedu podle lekcí naucse.python.cz
Vyskytl se mi problém ohledně Randomu. https://naucse.python.cz/course/pyladies/beginners/functions/
zkopírovaný kód z webu:
from random import randrange

cislo = randrange(0, 3)  # číslo je od 0, 1, nebo 2
if cislo == 0:
    print('Kolečko')
elif cislo == 1:
    print('Čtvereček')
else:  # 2
    print('Trojúhelníček')

výsledek po spuštění programu v comanderu:

(venv) C:\naucse-python\02>random.py
Traceback (most recent call last):
  File "C:\naucse-python\02\random.py", line 1, in <module>
    import random
  File "C:\naucse-python\02\random.py", line 2, in <module>
    from random import randrange
ImportError: cannot import name 'randrange' from 'random' (C:\naucse-python\02\random.py)

Nevím si s tím rady. Za případné typy děkuji.

**Comment by hroncok** [comment]
Ahoj nemůže se soubor jmenovat random.py. Když uděláš import random, hledá to Python nejprve soubor random.py ve stejné složce a až pak teprve v systémové složce, kde jsou tyhle věci (říká se jim moduly).

**Comment by hroncok** [comment]
On se pak vlastně naimportuje ten tvůj soubor, ale tam není funkce randrange.

**Comment by MartinJaks** [comment]
Čili mám špatně pojmenovaný program?

**Comment by hroncok** [comment]
Víceméně ano. Poučení je nepojmenovávat soubory stejně jako věci, co se importují.

**Comment by MartinJaks** [comment]
(venv) C:\naucse-python\02>nahoda.py
  File "C:\naucse-python\02\nahoda.py", line 5
    print('Kolečko')
        ^
IndentationError: expected an indented block

**Comment by MartinJaks** [comment]
Děkuji!

**Comment by hroncok** [comment]
No to už je jinej problém

**Comment by hroncok** [comment]
Založil jsem https://github.com/pyvec/naucse.python.cz/pull/428 - pomohl by ti tento text, kdyby byl ve studijních materiálech?
