### ISSUE TITLE
API se seznamem lekcí a materiálů

### ISSUE THREAD

**Issue by messa** [pyvec/naucse.python.cz#431]
Ahoj,

potřeboval bych se dostat k seznamu lekcí a materiálů v nich, abych to mohl zobrazovat v odevzdávacím toolu. Hlavní funkcionalita toho toolu bude, že u jednotlivých lekcí bude možné odevzdat domácí úkoly, ale proč tam rovnou už nepřidat i ty materiály :) Vlastně pak může nahradit stránku kurzu na naučse. Samotný obsah materiálů by ale zůstal na naučse.

Představuju si zhruba něco takového, že by mohlo být např. dostupné na nějaké URL: [course.yaml](https://github.com/messa/pyladies-courseware/blob/c3920115fd7e5e5b9bfb1bac134cf2595360e5ad/courses/pyladies_2018_praha_jaro_ntk/course.yaml)

V podstatě je to to samé, jako [zdrojová data naucse](https://github.com/pyvec/naucse.python.cz/blob/archived2018/runs/2018/pyladies-praha-jaro-ntk/info.yml), ale ideálně bez té dědičnosti okolo (`derives: pyladies`, `base: hello`) a v co nejstabilnějším formátu.

**Comment by encukou** [comment]
Tohle API by naucse mělo používat i interně, abychom měli jistotu, že tam je vše co frontend potřebuje.

**Comment by encukou** [comment]
Na tuhle issue jsem zapomněl a založil https://github.com/pyvec/naucse.python.cz/issues/512
Každopádně API je tak je popsáno tady :)
