### ISSUE TITLE
Místo pro statické soubory k běhu kurzu

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/naucse.python.cz#432]
Chtělo by to ke každému běhu kurzu mít nějakou složku, kam by se dalý dávat soubory jako:
* Zadání domácích projektů (dokud nebude vyřešeno jinak)
* Úvodní prezentace, která se mění s každým během a místem
* Feedbacky k domácím projektům, které se také s každým během mění

Znamenalo by to snazší úpravy a jednodušší práci, když bude vše ke kurzu na jednom místě a nebude se to míchat s ostatními městy.

Narazil jsem na to při přípravách dalšího kurzu, protože tyto tři skupiny souborů jsou ty jediné, kvůli kterým se ještě odkazuji na pyladies.cz

**Comment by frenzymadness** [comment]
Opět se mi to připomnělo, protože při přípravách feedbacku k domácím projektům musím nahrát obsah samotný na PyLadies.cz a pak ještě měnit linky v plánu na naucse.

**Comment by messa** [comment]
@frenzymadness  Co je to "feedback k domácím projektům"? Zatím jsem viděl jen feedback k odučené hodině (lekci).

**Comment by hroncok** [comment]
https://naucse.python.cz/2018/pyladies-ostrava-podzim/ -> Feedback k domácím projektům

**Comment by encukou** [comment]
Tož mám napůl hotové, ale nezdá se mi to, a přijde mi že všechny *use cases* by šly vyřešit speciálními lekcemi.

* Zadání domácích projektů
  * To by mohlo být jako lekce v HTML. V Ostravě myslím netisknete, je to tak?

* Úvodní prezentace, která se mění s každým během a místem
  * Tohle by opět mohlo být jako “lekce”. Dokonce to není jen tak ledajaký statický soubor – potřebuje se to odkazovat na jiné statické soubory, může v tom být škodlivý Javascript...

* Feedbacky k domácím projektům, které se také s každým během mění
  * Tohle by taky mohlo být jako lekce, dokonce relativně bez problémů – ipynb renderování funguje.

**Comment by encukou** [comment]
Pokecali jsme s Lumírem a vypadá to schůdně. Všechny use cases se teď řeší jinde.

### Zadání domácích projektů
Zkusil jsem to přímo v HTML/Markdown a je to docela opruz. Navíc chceme dle možností co nejvíc synchronizovat s Courseware.
Proto bych rád přidal možnost načíst data z YAML a vykreslit je šablonou. PR zde: https://github.com/PyLadiesCZ/naucse.python.cz/pull/21

### Úvodní prezentace, která se mění s každým během a místem.
Toto není moc prioritní, ale založil jsem https://github.com/pyvec/naucse.python.cz/issues/520

### Feedbacky k domácím projektům, které se také s každým během mění
Přidej jako ipynb "Lekce". Mělo by to fungovat hladce; dej vědět jestli budou jakékoli problémy.
