### ISSUE TITLE
Stahování forků

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/naucse.python.cz#433]
Už jsem se o tom zmínil na Slacku před nějakou dobou. Složka `.arca` má u mě na disku celkem 410 MB a stahování forků při spuštění naučse trvá celkem dlouho.

Bylo by možné změnit implementaci tak, aby se forky stahovaly až při kliknutí na konkrétní kurz a nikoli už při kliknutí na jejich seznam? Znamenalo by to úsporu místa a času snad pro všechny, protože jen málokdo při lokálním spuštění naučse potřebuje procházet opravdu všechny kurzy.

**Comment by hroncok** [comment]
Při lokálním použití by se forky neměly tahat vůbec.

**Comment by encukou** [comment]
> Bylo by možné změnit implementaci tak, aby se forky stahovaly až při kliknutí na konkrétní kurz a nikoli už při kliknutí na jejich seznam? Znamenalo by to úsporu místa a času snad pro všechny, protože jen málokdo při lokálním spuštění naučse potřebuje procházet opravdu všechny kurzy.

Ne, protože forky obsahují jméno kurzu :(

> Při lokálním použití by se forky neměly tahat vůbec.

Přesně tak; když nenastavíš `ARCA_BACKEND=arca.backend.DockerBackend` a tak, ukážou se jen kurzy co nejdou z forku.

**Comment by frenzymadness** [comment]
Já si je povoluju ručně pomocí proměnné prostředí, když potřebuji otestovat, že můj linkovaný fork funguje správně.

`FORKS_ENABLED=true PYTHONPATH="." python -m naucse serve`

No ale pokud to jinak nejde, tak se nedá nic dělat.

**Comment by encukou** [comment]
Něco se dělat dá; řeším v rámci https://github.com/pyvec/naucse.python.cz/issues/431

**Comment by encukou** [comment]
`FORKS_ENABLED` pustí kód ze všech forkům. Ne všem autorům nutně věřím, a nemůžu zaručit že naucse/arca ten kód izolují od tvého prostředí :(

**Comment by encukou** [comment]
Teď se stahují jen forky zapsané v `NAUCSE_TRUSTED_REPOS`.
Dál obsah rozdělujeme; cíl je lokálně ukázat obsah jen z aktuálního repozitáře.
