### ISSUE TITLE
Rebuild se po změně forku nespustí

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/naucse.python.cz#443]
@jas02 řeší problém, že se po změně v jeho forku naučse neprovede rebuild hlavního repozitáře. Většinou to vyřeším ručním spuštěním rebuildu v Travisu, ale chtělo by se na to podívat.

Rebuild byl například proveden po sloučení PR (https://github.com/pyvec/naucse.python.cz/pull/416), ale neprovedl se po přidání commitu do forku (https://github.com/jas02/naucse.python.cz/commit/3f9154fddc3461f0901e3be0520dca8b18a4068a).

Kouknul jsem se do svého forku na webhook a vidím, že i u mě poslední volání nebylo úspěšné, protože hook vrátil 500.

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at hooks.nauc.se Port 443</address>
</body></html>
```

**Comment by hroncok** [comment]
Možná https://github.com/pyvec/naucse-hooks/issues/8

**Comment by mikicz** [comment]
Sakra práce. Ten issue pyvec/naucse-hooks#8 to není, protože se to k tomu ani nestihlo dostat. Promazával jsem na serveru session, ale smazal jsem celou složku, nicméně uživatel pod kterým to beží neměl právo si novou vytvořit, takže teď nefungovalo hooks vůbec :( Sorry, teď už by to mělo běhat.

**Comment by mikicz** [comment]
To uzavření byl omyl

**Comment by frenzymadness** [comment]
Vidím asi 12 hodin starý commit (https://github.com/jas02/naucse.python.cz/commit/aac4043c51693d1c6047b6ba5e7989b6ca9ce030) a k němu odpovídající úspěšný build (https://travis-ci.org/pyvec/naucse.python.cz/builds/424535462) a stránku na webu (https://naucse.python.cz/2018/tieto/beginners/tieto-conditionals-loops/), takže je asi vše v pořádku.

Díky.
