### ISSUE TITLE
V návodu na vytvoření kurzu jsou requirements.txt, což je zřejmě neaktuální

### ISSUE THREAD

**Issue by zuzejk** [pyvec/naucse.python.cz#445]
https://naucse.python.cz/course/meta/meta/installing-naucse/

**Comment by encukou** [comment]
@mikicz najdeš si na tohle čas a chuť, ideálně tento/příští týden, nebo to mám vyřešit?

**Comment by mikicz** [comment]
O víkendu pošlu PR
