### ISSUE TITLE
Twitter API is now extremely hard to get into

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#453]
We should get it out of https://naucse.python.cz/course/mi-pyt/intro/requests/ and either get a different example (httpbin at worst, better some cool and **known** service).

Ideas (without checking their API availability):

 * instagram (we can post things there and see them)
 * imdb (cool for stats, too)
 * spotify (cool for stats, too, got very good structured data about tones etc.)
 * bit.ly or another url shortener (easy)

**Comment by encukou** [comment]
* YouTube?

**Comment by hroncok** [comment]
bit.ly gives me invalid login whatever I do and it also provides permanent tokens for such purposes :(
