### ISSUE TITLE
Zobrazit na webu obsah Jupyter/IPython notebooku

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#50]
Některé materiály (např. MI-PYT) obsahují Jupyter/IPython notebook.

Mělo by být poměrně jednoduché ten notebook rozparsovat (je to JSON) a zobrazit obsah, který může být různého typu, ale pro naše potřeby nás zajímá  (= v materiálech je) jen `markdown` (to už umíme) a `code` (to obalíme `<pre>` apod.), výstup pak může být plaintext nebo HTML.

**Comment by encukou** [comment]
Tohle je potřeba udělat nejpozději do nejbližší prezentace Pandas, která bude v Brně cca 25. 4. (To znamená že když to nebude, napíšu to sám...)

Zatím se naucse docela mění, takže jestli na tom něco uděláš, neměj privátní větve na svém počítači a radši prosím pošli WIP PR.

**Comment by hroncok** [comment]
Udělám samostatné repo, které to bude umět, pak se to zapojí sem jako knihovna. Aby se to dalo použít i na MI-PYT Edux.

**Comment by kvbik** [comment]
github umi ipy notebooky zobrazovat, ne?

**Comment by hroncok** [comment]
Ten jo. Proto to je zatím řešené odkazem.

Dne 1. 3. 2017 12:18 napsal uživatel "Jakub Vysoký" <
notifications@github.com>:

**Comment by kvbik** [comment]
Aha! Jasny. Sorry, nemam kompletni info. Tak jsem se jenom bal, aby vam neco neuniklo :D jinak myslim, ze jsou nejaky parsovace ipy notebooku, ktery z nej udelaji staticky html.

**Comment by encukou** [comment]
Koukni na https://github.com/jupyter/nbconvert, jestli nevynalézáš kolo. Ale jestli existující kolo natvrdo potřebuje pandoc nebo nějaký javascripty nebo tak, tak asi chceme menší kolo.

**Comment by hroncok** [comment]
Nepotřebuje pandoc. Tohle se nainstaluje pokud chci z Pythonu načíst notebook a vydumpovat z něho HTML:

```
bleach==1.5.0
decorator==4.0.11
entrypoints==0.2.2
html5lib==0.9999999
ipython-genutils==0.1.0
Jinja2==2.9.5
jsonschema==2.6.0
jupyter-client==5.0.0
jupyter-core==4.3.0
MarkupSafe==0.23
mistune==0.7.3
nbconvert==5.1.1
nbformat==4.3.0
pandocfilters==1.4.1
Pygments==2.2.0
python-dateutil==2.6.0
pyzmq==16.0.2
six==1.10.0
testpath==0.3
traitlets==4.3.2
```

Asi bych to teda použil.

**Comment by hroncok** [comment]
Plánuju to dělat na #minisprint - předpokládá se zatím 18.3. což je víc než měsíc před deadlinem.

**Comment by encukou** [comment]
#minisprint nebyl; (jaký) je nový plán?

**Comment by hroncok** [comment]
Můžu na tom dělat dneska, až dodělám #67
