### ISSUE TITLE
Python - cmd - Invalid Syntax

### ISSUE THREAD

**Issue by TheQwertz** [pyvec/naucse.python.cz#522]
Ahoj,
vytvořil jsem prostý program typu "Hello world!", uložil do speciálního adresáře a přes cmd pokusil spustit.

Hello, I have created simple program like "Hello World", i saved that into special directory, and in cmd I tried to launch it, just like in one tutorial, I am learning from.

![dsd](https://user-images.githubusercontent.com/47478373/52521971-b1627800-2c7f-11e9-9757-4da82072c509.png)

Napsalo mi to SyntaxError, viz. screen.
Neví někdo, v čem to tkví? Vše teprve zjišťuji.

It writes SyntaxError.
I am newbie. Can someone help?

(Sorry for crappy English, I am not native.)

**Comment by encukou** [comment]
V prvním programu by měl být jen řádek:
```
print('Hello world')
```

**Comment by TheQwertz** [comment]
Nechápu to, dělám to přesně jako oni, primitivní návůdek, a buďto SyntaxError, nebo že to nelze otevřít, protože tam žádný takový soubor není. No, nevadí.

**Comment by encukou** [comment]
Jestli dostáváš i jinou chybu, napiš prosím celou chybovou hlášku. Bez ní se těžko hádá, co je špatně.

**Comment by TheQwertz** [comment]
![image](https://user-images.githubusercontent.com/47478373/52592640-3350cd80-2e47-11e9-94a8-2588cf880c93.png)
![py1](https://user-images.githubusercontent.com/47478373/52592644-377ceb00-2e47-11e9-891c-99767bef92d6.png)

Píše mi to, že daný soubor neexistuje. Zkusil jsem "python ahoj.py" i "python ahoj.py.py" (kvůli jménu) a dalších několik způsobů.

**Comment by hroncok** [comment]
Co je v tom souboru?

**Comment by TheQwertz** [comment]
Pouze jednoduchý print('Hello World') nebo tak.

**Comment by elchupacabra666** [comment]
Zdar mám taky problém s tímto "úkolem".
![Bez názvu](https://user-images.githubusercontent.com/62707746/77659176-017dc600-6f78-11ea-82cc-88843f71b61a.png)
