### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by TomasRoj** [pyvec/naucse.python.cz#539]
Hey,

I want to change some things on your site. How do I add link to some editor for example? Can I just paste the link or must do something extra?

**Comment by hroncok** [comment]
Depends on where. The lessons are usually formatted in [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links).

**Comment by TomasRoj** [comment]
I want to change something in this file: lessons/beginners/install-editor/index.md

**Comment by hroncok** [comment]
There are some links in the bottom of that page (for PyCharm, Eclipse nebo KDevelop). So you can see how it is done.

**Comment by TomasRoj** [comment]
Ok, thanks for help.
