### ISSUE TITLE
Proposal: Strictly separate content and templates

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#56]
(This is an idea I've got after reading the discussion in https://github.com/pyvec/naucse.python.cz/pull/55#discussion_r105122650, although it's not related to the discussion itself, so I'm opening a new issue not to spam that discussion).

See [this template](https://github.com/pyvec/naucse.python.cz/blob/084ee3dae963705de01cdb4aa3b7d9398243c4f0/naucse/templates/index.html). It has content. It says things. I propose we remove the content form the template and save it somewhere where content belongs, such as in this repository a YAML or Markdown file.

Does it make sense?

(This is not intended as bikeshedding, feel free to ignore the proposal until more pressing issues are fixed.)

**Comment by Sanqui** [comment]
I believe that is already being done for lessons.  I can see some lessons have already been converted to Markdown, e.g. [cmdline](https://github.com/pyvec/naucse.python.cz/blob/master/lessons/beginners/cmdline/index.md).  However, it's more complicated for templates for e.g. the front page, which aren't simply formatted text, rather websites with various elements - buttons, containers, cards.  Those may be expressed easier in explicit HTML.

**Comment by encukou** [comment]
Yeah, the home page is special – it mixes short pieces of text and formatting, and it's quite visual. I think separating here would make it quite a lot harder to edit.
For more content-heavy pages, this should be done already.
