### ISSUE TITLE
[beginners] Přesunout virtuální prostředí na později

### ISSUE THREAD

**Issue by Kobzol** [pyvec/naucse.python.cz#584]
Přijde mi zbytečné zatěžovat účastnice hned v první lekci s virtualenvem.
Je to mentální zátěž navíc, musí kvůli tomu pokaždé myslet na to, jestli jsou ve venvu nebo ne a je těžké jim říct motivaci (v té době netuší, co jsou knihovny).
Naživo při kurzu z toho byli lidi zmatení a byl to IMO zbytečný black magic.
Navrhuji přesunout ho do pozdější lekce, kde bude potřeba poprvé použít externí knihovnu.

Motivací pro použití venvu (kromě správy knihoven, což ale v této lekci zatím nepotřebují), možná předtím bylo, že budou mít jednotný `python` příkaz, jak na Linuxu, tak na Windowsu. Nicméně na nových instalacích Pythonu na Windows už příkaz `python` normálně funguje out of the box, takže venv k němu nepotřebují.

V instalaci Atomu se sice instaluje `flake`, ale to bude fungovat i pro globální instalaci, navíc tak to je možná i lepší pro tenhle konkrétní balíček a ukázka instalace `flake` stejně nepoužívá venv.

Výhody:
- Rychleji se přejde k vyzkoušení Pythonu
- Z lekcí před moduly můžou zmizet zmínky o tom, že musí mít aktivovaný venv

Nevýhody:
- Nebudou od začátku navyklé na používání venvu. Nicméně v pozdější lekci už budou zkušenější a nemyslím, že by byl problém jim to vysvětlit opravdu až ve chvíli, kdy budou potřebovat první externí knihovnu. Navíc tak získají lepší insight, že venv jim slouží hlavně pro jednodušší práci s knihovnami. Teď to spíše vypadá jako black-box, který musím pokaždé udělat, když chci spustit Python.
- Je třeba určit jiné místo, kde se jim venv ukáže.

**Comment by encukou** [comment]
Nesouhlasím.
Kdyže instaluje první knihovna, venv nedává o moc víc smyslu než na úplném začátku. Přeučovat se na nový proces taky není úplně lehké.
Na nových instalacích Pythonu na Windows příkaz "python" funguje, ale jsou i starší instalace nebo instalace kde `python` z nějakého důvodu není v PATH. Kromě toho je tu Linux a Mac, kde by sice `python` taky měl fungovat, ale není tomu tak vždycky.

Situace s Atomem a flake8 je docela nepříjemná. Rád bych se co nejvíc vyhnul globálním instalacím: mělo by být možné počítač vrátit po kurzu/workshopu do původního stavu, když člověk zjistí že to není pro něj. S venvem jde tohle krásně.

> Z lekcí před moduly můžou zmizet zmínky o tom, že musí mít aktivovaný venv

Ale které lekce jsou před moduly? Jednotlivé lekce se dají pro různé kurzy přehazovat. Samozřejmě je jde parametrizovat nebo limitovat možné pořadí, ale je lepší se tomu vyhnout.

---

Ale ve svém kurzu to samozřejmě klidně zkus! :)

**Comment by Kobzol** [comment]
Tak pokud Python není v PATH, tak ani ten venv nepůjde jednoduše vytvořit :-)

Vrácení do původního stavu nejspíše znamená odinstalovat python, což by i knihovny odstranilo. Zrovna flake8 je taková metaknihovna, která je spíše pro IDE/CLI použití, takže z mého pohledu patří spíše do globální instalace než do virtualenvu.

Nevěděl jsem ale, že ty lekce se někdy přehazují, pak by bylo složité najít bod, kde venv představit. Takže tahle změna asi nemá smysl :-)

**Comment by hroncok** [comment]
Já také nesouhlasím.

 - Motivace pro stejný příkaz `python` je stále validní na Macu i na různých linuxových distribucích.
 - Je třeba to od začátku vyučovat a „natlouct“ jim to do hlavy od začátku, ne je později přeučovat.
 - Flake8 do Atomu považuju za zbytečný.

**Comment by Kobzol** [comment]
Máš pravdu, díky tomu příkazu je to pak jednotné a jednodušší, na OS X jsem nemyslel a může být problém s Pythonem 2 na Linuxu. A jak už jsem psal, kvůli různému pořadí lekcí to musí zůstat na začátku.

Na druhou stranu, učit je něco dogmaticky asi není úplně potřeba. Python se dá v pohodě používat i bez virtuálního prostředí, takže bych to nebral tak, že jim musíme říkat, že virtualenv je naprosto nezbytná věc. Ideální by samozřejmě bylo, kdyby ho Python podporoval built-in, ale na to už je asi trochu pozdě :)

**Comment by hroncok** [comment]
BTW Python to podporuje builtin (`venv`) a je třeba si dát pozor na termín virtualenv.

**Comment by Kobzol** [comment]
Myslel jsem spíše kdyby Python podporoval lokální scope balíčků a pořádný balíčkovací systém by default, např. jako npm pro JS nebo Cargo pro Rust :) Pak by celá tahle sranda s virtuálním prostředím nebyla potřeba.
