### ISSUE TITLE
Navigace v hlavičce

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/naucse.python.cz#6]
Navrhuji přidat do hlavičky odkaz na návrat na hlavní stranu resp. odkaz na návrat o úroveň výše.

**Comment by encukou** [comment]
Napřed obsah, potom navigaci! Ale v podstatě souhlasím. Jen ta "úroveň výše" se nedá dost dobře nadefinovat, pořadí jednotlivých tutoriálů může být různé.

**Comment by encukou** [comment]
Už jsou tam breadcrumbs.
