### ISSUE TITLE
Colorized shell output in Markdown

### ISSUE THREAD

**Issue by encukou** [pyvec/naucse.python.cz#61]
The [PyLadies materials for Git](http://pyladies.cz/v1/s009-git/git.html) use HTML for colorized shell output. Is there a better way? How to do this in Markdown?

**Comment by hroncok** [comment]
Keep the color escape codes and write a plugin for the Markdown parser that converts them to color?

**Comment by benabraham** [comment]
I use https://highlightjs.org/ on client. Many syntaxes, many color themes.

**Comment by hroncok** [comment]
Here we use Pygments.

**Comment by encukou** [comment]
Pygments also has many syntaxes and color schemes for syntax highliting. This is not about syntax highlighting, though.

Als, no JS please. All this could end up printed in a book.

**Comment by benabraham** [comment]
I get it now. Sorry for OT. @hroncok's idea is probably the best. 
It will be mostly copy&paste when created. 
A question is if it will be easy enough to edit such source.

**Comment by Sanqui** [comment]
I believe [ansi2html](https://pypi.python.org/pypi/ansi2html) can be used for this.

**Comment by hroncok** [comment]
https://github.com/pyvec/naucse.python.cz/blob/e2c0ea93799e64e760dc51f5de948b1cbb3a5145/naucse/markdown_util.py#L63

Seems easy!

```python
from ansi2html import Ansi2HTMLConverter
ansi_convertor = Ansi2HTMLConverter()

...

        if lang == 'ansi':
            converted = ansi_convertor(code, full=False)  # already escapes HTML (do we need to use some Markup() equivalent in mistune?)
            return '<div class="codehilite"><pre><code>{}</code></pre></div>'.format(converted)
            
```

**Comment by encukou** [comment]
Reopening this – it still should be possible to do it in a more elegant way.

**Comment by hroncok** [comment]
GitHub umí tohle:

    ```patch

```patch
diff --git a/setup.py b/setup.py
index 3a69792..6b453ab 100644
--- a/setup.py
+++ b/setup.py
@@ -11,7 +11,7 @@ setup(
     keywords='holiday,dates',
     license='Public Domain',
     url='https://gist.github.com/oskar456/e91ef3ff77476b0dbc4ac19875d0555e',
-    py_modules=['isholiday'],
+    packages=['isholiday'],
     classifiers=[
         'Intended Audience :: Developers',
         'License :: Public Domain',
```

Nevyřešilo by to všechny případy, ale pro diffy/commity by to vypadalo dobře i na githubu i na webu, kdybychom měli pro pygments takový lexer.

**Comment by encukou** [comment]
Mám za to že v Pygments se jen jinak jmenuje – [`diff`](http://pygments.org/docs/lexers/#pygments.lexers.diff.DiffLexer)

**Comment by hroncok** [comment]
Když jsme to použil, vypadalo to jako plaintext. Možná něco dělám špatně.

**Comment by encukou** [comment]
Still not ideal, but I don't think it makes sense to track this here – there'll always be something more inportant.
