### ISSUE TITLE
PyLadies Praha tahák na command linu: připomínky

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#612]
Na https://naucse.python.cz/2020/pyladies-praha-jaro2020-barclays/ je "[tahák na příkazovou řádku a první kroky v Pythonu](https://s3-eu-west-1.amazonaws.com/messa-shared-files/2017/09/pyladies_2_lekce_tahak.pdf)"  -- v kanonickém kurzu není a dokaz vede někam k @messa. Na [pyladiescz/naucse.python.cz](https://github.com/pyladiescz/naucse.python.cz) nejsou povolené issues, tak zakládám tady.

- `~/muj_adresar\muj_venv\Scripts\activate` míchá druhy slashů je matoucí. učíme `venv\Scripts\activate`, ne `~/muj_adresar\muj_venv\Scripts\activate`
- chybí `rmdir`, viz https://github.com/pyvec/naucse.python.cz/issues/611
- `Negace (-5)` mi nedává smysl

**Comment by encukou** [comment]
> Na pyladiescz/naucse.python.cz nejsou povolené issues,

To je standardní chování forků na GitHubu, ale v tomhle případě myslím že by měly být povolené. Nastavil jsem to a založil https://github.com/PyLadiesCZ/naucse.python.cz/issues/75

Tady zavírám jako duplikát https://github.com/pyvec/naucse.python.cz/issues/52
Jako pro všechny materiály, bylo by super tahák vypilovat ve forku a pak začlenit sem. (Tahák do cheatsheets + sem dát odkaz.)
