### ISSUE TITLE
[beginners/hello-world] nejde mi to

### ISSUE THREAD

**Issue by elchupacabra666** [pyvec/naucse.python.cz#615]
Zdar. Dělám úkol s názvem první program, ale když napíšu python ahoj.py tak to napíše chybu.
![Bez názvu](https://user-images.githubusercontent.com/62707746/77662711-81a62a80-6f7c-11ea-8245-98122e0093d1.png)

**Comment by encukou** [comment]
Tohle se často stává když máš poškozený virtualenv. To se může stát třeba tak, že ho přesuneš na jiné místo.
Zkus virtuální prostředí (adresář `venv`) smazat a [vytvořit znovu](https://naucse.python.cz/course/pyladies/beginners/venv-setup/).

---

Sem (*issues* na GitHubu) patří úkoly, které je potřeba udělat na webovkách. Tohle není úkol, proto to zavřu; klidně sem ale piš dál kdyby byly problémy.

**Comment by elchupacabra666** [comment]
Jsem si říkal, že to nějak dlouho trvalo. Sorry že vám v tom dělám bordel. Problém byl přesně v tom, co jsi napsal. Díky ti a hezký večer.
