### ISSUE TITLE
Git jako součást Pythonu

### ISSUE THREAD

**Issue by tereya** [pyvec/naucse.python.cz#618]
Pozn. ke https://naucse.python.cz/course/pyladies/ Lekce 4 – Správa zdrojového kódu Git 👍 
Myslm, že tam hodně chybí zmínka o tom jak pracovat s Git, když pracují na kodu dva lidé! Tj. chybí mi tam vysvětlení a příkaz, že než začnu pracovat, měl bych si stáhnout z git aktuální verzi (změny ostatních)..  = prostě není tam vůbec zmínka o **git pull**
P.S. Ten kurz je super!!!

**Comment by encukou** [comment]
Je to až v lekci 7. Materiálů o Gitu je hodně, tak to je rozdělené na dvě lekce, a mezi nimi se programuje.
Na prezenčních kurzech dává větší smysl; pro samostudium by se dalo všechno o Gitu vyčlenit do úplně samostatného kurzu.

> P.S. Ten kurz je super!!!

Díky!

**Comment by tereya** [comment]
Jasně že GIT může mít separátní kurz, ale když jste ho ..geniálně mimochodem-- dali hned na začátek a zvládli ho ve dvou krátkých článcích (fakt je to dobře, moc mi to pomoholo), tak si myslím, že to chce odstavec o =git pull=, nezdá se to možná, ale použije se to = já teď např. dělám v práci jednodušší úpravy nějakého home made webu a používá se i git, musím zvládnout git na nízké úrovni - a vždy začít pullem(!). 
Myslím totiž, že někdo reálně použije vaše články o GITu separátně k pochopení základu gitu (protože jsou dobře napsané) a proto pull chybí v úplném základu. Je to odstavec kurzivou = "v případě že by na kodu pracoval někdo jiny, měli byste začít by git pull, více viz lekce 7"...

**Comment by encukou** [comment]
Bohužel před `git pull` je potřeba ještě `git clone`, a ideálně něco o vzdálených repozitářích, a už toho je dost na další lekci...

Změním to tu na přesunutí Gitu ven.

**Comment by tereya** [comment]
Tak to je PŘESNĚ to, co jsem nechtěla.  
Jsem věčný začátečník a nemůžu se dokopat přesoukat se přes lekce typu cykly, stringy apod. a to že je kurz "proložený" velmi velmi brzo (jednoduchym uvodem do) gitu, githubu, vyjimek apod je právě naprosto fantastické - konecne umim neco noveho z čeho můžu vycházet. 
Samotný python, samotný git, samotná přikazová řádka to je přesně to co v začátečnickém kurzu nechci a pochopila jsem to díky vám.
