### ISSUE TITLE
chyba [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by skrasi2104** [pyvec/naucse.python.cz#621]
Začal jsem se učit programovat Python a hned mám problém😒. Nejde mi spustit https://1url.cz/DzBES , hlásí mi to chybu [Errno 2] No such file or directory, používám příkazový řádek a   Visual studio code. pomoc

**Comment by encukou** [comment]
Jsi v příkazové řádce v tom adresáři, ve kterém máš uložený ten soubor?
Jaký používáš operační systém?

**Comment by skrasi2104** [comment]
Jsem v adresáři kde mám i venv. Používám Windows díky

**Comment by encukou** [comment]
Co vypíše příkaz `dir`?

**Comment by skrasi2104** [comment]
Microsoft Windows [Version 10.0.18362.778]
(c) 2019 Microsoft Corporation. Všechna práva vyhrazena.

C:\Users\simon>cd desktop

C:\Users\simon\Desktop>cd python

C:\Users\simon\Desktop\PYTHON>cd dva

C:\Users\simon\Desktop\PYTHON\DVA>py -3 -m venv venv

C:\Users\simon\Desktop\PYTHON\DVA>venv\scripts\activate

(venv) C:\Users\simon\Desktop\PYTHON\DVA>dir
 Volume in drive C has no label.
 Volume Serial Number is E246-C806

 Directory of C:\Users\simon\Desktop\PYTHON\DVA

12.05.2020  16:13    <DIR>          .
12.05.2020  16:13    <DIR>          ..
12.05.2020  16:13    <DIR>          venv
               0 File(s)              0 bytes
               3 Dir(s)  433 458 278 400 bytes free

(venv) C:\Users\simon\Desktop\PYTHON\DVA>
Tohle my vypíše dir ve složce kde je soubor ahoj.py, při použití příkazu python ahoj.py vypíše chybovou hlášku Errno 2😒😒

**Comment by skrasi2104** [comment]
podrobně napíše:
(venv) C:\Users\simon\Desktop\PYTHON\DVA>python ahoj.py
C:\Users\simon\AppData\Local\Programs\Python\Python38\python.exe: can't open file 'ahoj.py': [Errno 2] No such file or directory

**Comment by encukou** [comment]
```doscon
(venv) C:\Users\simon\Desktop\PYTHON\DVA>dir
Volume in drive C has no label.
Volume Serial Number is E246-C806

Directory of C:\Users\simon\Desktop\PYTHON\DVA

12.05.2020 16:13
.
12.05.2020 16:13 ..
12.05.2020 16:13 venv
0 File(s) 0 bytes
3 Dir(s) 433 458 278 400 bytes free
```
Tohle říká, že v adresáři `C:\Users\simon\Desktop\PYTHON\DVA` soubor `ahoj.py` není. Ověř si, že jsi ho opravdu uložil tam. Ulož ho opravdu do tohoto adresáře (třeba pomocí "Uložit Jako"/"Save As" v editoru).

**Comment by skrasi2104** [comment]
Děkuji moc, měl jsem to špatně uložené na desktopu.
