### ISSUE TITLE
MacOS: Chybí instalace git-ui (gitk)

### ISSUE THREAD

**Issue by Tendali** [pyvec/naucse.python.cz#646]
V návodu pro instalaci gitu na MacOS, chybí část ve které je nainstalován gitk, který se využívá v pozdějších částech kurzu.

Příkaz na instalaci gitk:
brew install git-gui

**Comment by encukou** [comment]
Aha, správci Homebrew [nedávno rozdělili `git` a `git-gui`](https://github.com/Homebrew/homebrew-core/commit/dfa3ccf1e7d3901e371b5140b935839ba9d8b706). Díky za upozornění!

Rád bych dal do materiálů instalaci obojího jedním příkazem. Funguje `brew install git git-gui`? (Nemám Mac, nemůžu to vyzkoušet.)

**Comment by Tendali** [comment]
Ano, vypadá to, že to funguje!
PS: Děkuji za odpověď.

**Comment by Glutexo** [comment]
Potvrzuji, že funguje.
