### ISSUE TITLE
Deployment na PythonAnywhere jako samostatná lekce

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/naucse.python.cz#652]
Rád bych přidal deployment webové aplikace jako samostatnou bonusovou lekci do kurzu, ale aktuálně to nejde, protože tato stránka je jen jako subpage jiné lekce.

Dávalo by smysl z toho udělat samostatnou lekci, která by klidně mohla být součástí lekce o deploymentu? Zjednodušeně `lessons/intro/deployment/pythonanywhere.md` → `lessons/intro/deployment/pythonanywhere/index.md`

**Comment by encukou** [comment]
Text o PythonAnywhere je podstránka lekce o deploymentu: https://naucse.python.cz/course/mi-pyt/intro/deployment/
Deployment samotný je samostatná lekce.

Ve svém kurzu to samozřejmě můžeš změnit dle potřeby, ale pro MI-PYT je to, myslím, takhle OK.

**Comment by frenzymadness** [comment]
A je nějak možné se na tu podstránku odkázat z programu kurzu a označit její obsah jako bonusový materiál?

**Comment by encukou** [comment]
Ne, tak jak to je se z programu dá odkázat jen na celou lekci, i s WSGI.

**Comment by frenzymadness** [comment]
Oukej, děkuji
