### ISSUE TITLE
Lekce Dědičnost - kapitola Polymorfismus - možná chybí kus příkladu?

### ISSUE THREAD

**Issue by Disi77** [pyvec/naucse.python.cz#656]
ahoj, v lekci Dědičnost - Polymorfismus je první část příkladu zakomentovaná, takže není vidět na naucse.python.cz (https://naucse.python.cz/course/pyladies/beginners/inheritance/)

je to záměr? myslím, že by se to tam mělo vrátit zpátky 😎

**Comment by frenzymadness** [comment]
Myslím si, že ty čtyři řádky stačí. Po mnoha příkladech výše si každý dokáže představit, jak zhruba ty třídy vypadají a právě ty poslední čtyři řádky jsou pro vysvětlení polymorfismu to nejdůležitější a v dlouhém kódu by to mohlo zapadnout.
