### ISSUE TITLE
Tykání

### ISSUE THREAD

**Issue by encukou** [pyvec/naucse.python.cz#66]
Jedna změna, kterou bych osobně rád udělal oproti MI-PYT, je tykání. Např. místo:

    Flask opět můžete nainstalovat do virtualenvu, …
    Například když v aplikaci výše navštívíme URL …

dát

    Flask opět můžeš nainstalovat do virtualenvu, …
    Například když v aplikaci výše navštívíš URL …

a tento styl použít v rámci celého naucse.

Je to stále vhodné pro vysokoškolské materiály? Nebo bude lepší tykat jen začátečníkům?

**Comment by whiskybar** [comment]
No jak jsi se už vlastne podřekl, můžeš použít i třetí tvar:

"Například když v aplikaci výše navštívíme URL"

vykání by bylo

"Například když v aplikaci výše navštívíte URL"

Skoro bych se primluvil za tu 1. osobu mnozneho cisla, "my navštívíme" URL.

**Comment by frenzymadness** [comment]
Nevím jak jiní, ale já bych na naucse plošně všem tykal. Příjde mi to více osobní a mě by takový tutoriál více "vtáhnul do děje", jestli chápete, co tím myslím.

**Comment by hroncok** [comment]
Mně se tykání v materiálech naopak nelíbí, web který mi tyká, považuju za infantilní. Vykání je v pohodě, protože ho čtu jako "oslovujeme více lidí", ne jako že mi  @encukou vyká.

**Comment by encukou** [comment]
Jo, pro kurz je vykání v pohodě, ale pro lidi co půjdou podle materiálů z domu už to není ideální. (A samotné „naucse“ je tak trochu infantilní...)

Pro MI-PYT tedy nechávám vykání.
