### ISSUE TITLE
Použití explicitního event loopu v lekci o grafice

### ISSUE THREAD

**Issue by Kobzol** [pyvec/naucse.python.cz#675]
Učil jsem nedávno studenty dělání jednoduchých her pomocí `PyGame` v Pythonu a `SDL` v C a porovnával to s tím, co se učí v základním kurzu PyLadies (pyglet). Chtěl bych nadhodit diskuzi o jedné věci, která mi přijde v PyLadies materiálech možná zbytečně matoucí.

Použitá knihovna `pyglet` má "schovaný" event loop, tj. pouze se zavolá `pyglet.app.run()`, který řídí event loop aplikace a reakce na eventy a kreslení se musí dělat pomocí callbacků (ať už s dekorátorem `@window.event` nebo s `window.push_handlers`):
```python
import pyglet
window = pyglet.window.Window()

def zpracuj_text(text):
    print(text)

window.push_handlers(on_text=zpracuj_text)

pyglet.app.run()
```

Z mých (velmi omezených) zkušeností z této lekce z Olomouce mi přišlo, že tohle může účastnice/účastníky mást. Doteď vždy víceméně ovládaly program*, ale tady najednou musí používat callbacky, které se volají v jim neznámou dobu z jim neznámého místa a nemusí být zřejmé, v jakém pořadí se funkce budou provádět. Asi nemusím vysvětlovat, proč callbacky můžou být mindfuck i pro zkušenější programátor(k)y :)

\* Až na želvičku, ale tam nebyly callbacky, program se provedl imperativně a pak se akorát bloknul pro vykreslení v okně.

# Návrh:
Používat explicitní event loop, aby šlo vidět, co přesně ten program dělá, a nemusely se používat "magické" callbacky. Pseudo-kód:
```python
running = True
while running:
     for event in window.get_events():
         if event == EVENT_QUIT:
            running = False
         elif event == KEY_LEFT:
            had_x -= 10
     had.draw(window)
     window.flip()  # vykreslení bufferu na obrazovku
```
Takto by ten program byl mnohem podobnější předchozím programům a šlo by jasně vidět, co se děje "uvnitř", tj. nebyla by to taková magie. Jednotlivá funkcionalita (např. reakce na klávesy, pohyb myši, kreslení atd.) by se stejně rozhodila do funkcí, ale už by je volaly sami, a nedělal by to za ně někdo jiný. Taky lze takto kód lépe krokovat (což ale nevím, jestli reálně využívají v této lekci).

# Nevýhody:
- `pyglet` sice nějak podporuje [explicitní smyčku](https://pyglet.readthedocs.io/en/latest/programming_guide/eventloop.html#dispatching-events-manually), ale není to úplně "first-class" citizen a všechny tutoriály fungují s callbacky. Při použití explicitní smyčky by se tak možná musela použít jiná knihovna než `pyglet`, což by vyžadovalo změnu spousty materiálů :(
- Některé věci (např. `schedule_interval`) by se musely nakódit ručně. Nepřijde mi to úplně špatně, ale byl by to trochu krok od tvorby hry k tvorbě herního enginu.
- Nebudou po této lekci znát callbacky (pokud bychom je nedali i do explicitního loopu).

Jak už jde vidět z dlouhého seznamu nevýhod :smile:, tak to nejspíše nestojí za tak velkou změnu, ale aspoň by mě zajímalo, jestli se s tímhle setkal někdo další a jestli jsou ty callbacky opravdu matoucí v živých kurzech, nebo jestli řeším prkotinu a účastnice/účastníci callbacky zvládají levou zadní.

**Comment by hroncok** [comment]
Podle mě je pochopení tohoto způsobu programování jeden z primárních cílů této lekce. Že u toho jsou obrázky a hýbají se je takový bonus.

**Comment by Kobzol** [comment]
Takže ve skutečnosti to je lekce na callbacky skrytá za čučavou grafikou jo :smile: Tak v tom případě to tedy cíl plní :)

**Comment by hroncok** [comment]
Nevím, jestli to byl @encukou'ův plán, ale já to tak mám, když to učím.

**Comment by encukou** [comment]
Jojo, je to lekce na callbacky. V celém kurzu jsou ty hry jenom příklady :)
Ale díky za návrh!
