### ISSUE TITLE
Problém při instalaci prostředí

### ISSUE THREAD

**Issue by Nikdo5** [pyvec/naucse.python.cz#679]
Zadám py -3 -m venv venv
a ukáže mi to:
Error: Command '['C:\\Users\\Adam \\Documents\\yes\\venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 101.

Verze pythonu 3.9 64 bit. Windows 10
co s tím?

**Comment by encukou** [comment]
Je to všechno, co se ukáže?
Podle chyby to vypadá že už máš virtuální prostředí vytvořené a aktivované, takže to znovu vytvářet nemusíš.

**Comment by encukou** [comment]
Zavřu tohle issue, ale kdyby se to stalo znovu nebo bys měl/a víc informací tak se prosím ozvi.
