### ISSUE TITLE
Lesson about GitHub: deprecation notice after login

### ISSUE THREAD

**Issue by adelpopelkova** [pyvec/naucse.python.cz#686]
When using username and password to authenticate to GitHub, you get an email with deprecation notice saying that you will need a token to authenticate. The email is linking [here](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/). If I understood it correctly it happens only when you use HTTPS.

**Comment by hroncok** [comment]
https://github.com/pyvec/naucse.python.cz/issues/670
