### ISSUE TITLE
MI-PYT: Requests a click existuje dvojitě

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#69]
...jednou dohromady a jednou rozděleně. Je třeba se na to podívat a vyřešit to.

**Comment by encukou** [comment]
Ktomě toho tykání, které je potřeba přendat zpátky na vykání, vypadají ty rozdělené stránky OK?

**Comment by hroncok** [comment]
Vypadají OK. Nekontroloval jsem to 1:1.
