### ISSUE TITLE
Struktura

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/naucse.python.cz#7]
Aktuální struktura respektuje to, jjak sou jednotlivá témata probírána v rámci kurzů PyLadies. Chceme to takto i zde?

Jde mi o to, že návštěvník se musí proklikat strukturou, která mu třeba na první pohled nemusí dávat smysl a může komplikovat navigaci jako takovou. Další nevýhodou je nutnost udržovat samostatné hlavní stránky pro každou lekci, které ale většinou obsahují jen odkazy na samotné materiály.

Možnost je udělat jednu velkou společnou úvodní stranu, kde bude pár slov k projektu jako takovému a pod tím kompletní obsah, který může být stále pro přehlednost zobrazen ve více úrovních odsazení (jako obsah knihy).

**Comment by encukou** [comment]
Ne. Adresářová struktura by ideálně měla být plochá – pro každý tutoriál adresář s html šablonou a třeba nějakými obrázky.
Pak kolem toho bude potřeba postavit "navigační strukturu" (obsah) – nejspíš i několik; v PyLadies se pořadí a probíraná témata pro každý běh trochu mění.

**Comment by frenzymadness** [comment]
Otázka zodpovězena, uzavírám. Strukturu pak budeme řešit obsáhleji po migraci obsahu.
