### ISSUE TITLE
pong doesn't work 

### ISSUE THREAD

**Issue by JanKuris** [pyvec/naucse.python.cz#730]
i have issue with pong code. 
 module 'pyglet.gl' has no attribute 'glBegin'

**Comment by encukou** [comment]
Viz https://github.com/pyvec/naucse-python/issues/27

Aktuální verze Pongu bude fungovat se starší verzí Pygletu, kterou nainstaluješ pomocí:
```
python -m pip install "pyglet<2"
```

**Comment by encukou** [comment]
Na webu už je nová verze.
