### ISSUE TITLE
License for the code

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#88]
We've talked about this with @encukou but I don't want to forgot it.

This repo is getting more and more code, but it has no implicit license, thus in theory the code is not free / open source software.

Apart form code, we also have content, but the content is usually has it's license specified in the metadata. Co I have the following proposal:

License the code with the MIT/Expat license (author "naucse.python.cz contributors") and say that the content has it's own license in the metadata (and fallbacks to CC BY-SA 4.0 if not specified).

------------------------

Agreed to license the code (not content) with the [MIT license](https://opensource.org/licenses/MIT) with "naucse.python.cz contributors" as `<COPYRIGHT HOLDER>`:

 * [x] @encukou
 * [x] @hroncok
 * [x] @Krejdom 
 * [x] @frenzymadness 
 * [x] @Sanqui 

The following contributors only added content (not mentioning them to not bother them):

 * Glutexo 
 * asgeirrr 
 * vasekch 
 * honzajavorek (also deleted CNAME, which is fine)
 * zuzejk 
 * lspdv
 * Aprillion 
 * stlk 
 * zoellenka 
 * andrenvk 
 * budinm1 
 * petrblaho 
 * baradrb 
 * jirutka 
 * tulinkry 
 * ggljzr 
 * MarekSuchanek 
 * vknaisl 
 * rludva

**Comment by encukou** [comment]
+1, except the fallback to CC-BY-SA is problematic: if there's no license info, there's also no author info.

Could you add license info to MI-PYT lessons?
I'll add it for the beginners' lessons by mid-May, as part of converting to Markdown.
After that, naucse should enforce that each lesson has a license.

**Comment by hroncok** [comment]
Ok. For MI-PYT, the authors are us plus several other contributors. We coul:

 * say Petr Viktorin, Miro Hrončok and other MI-PYT contributors
 * name everyone (will be a horrible nightmare to keep updated)
 * use some kind of macro, that finds it out from git (might be overkill)

Dne 7. 4. 2017 12:05 napsal uživatel "Petr Viktorin" <
notifications@github.com>:

**Comment by encukou** [comment]
I think "Petr Viktorin, Miro Hrončok and other MI-PYT contributors" is fine. Others can always add themselves to that list. And once each page links to GitHub, the gallery of contributors will be a click away.

**Comment by hroncok** [comment]
According to GitHub, there are 24 contributors of this repo. I will go one by one and check whether it's code contribution or not, than I'll ask affected people to agree here with MIT.

**Comment by hroncok** [comment]
I agree to license the code (not content) with the [MIT license](https://opensource.org/licenses/MIT) with "naucse.python.cz contributors" as `<COPYRIGHT HOLDER>`.

**Comment by hroncok** [comment]
@encukou, @Krejdom, @frenzymadness and @Sanqui, please state your position.

**Comment by Sanqui** [comment]
I agree to license the code (not content) with the MIT license together with "naucse.python.cz contributors" as Sanqui.

**Comment by Krejdom** [comment]
I agree to license the code (not content) with the MIT license with "naucse.python.cz contributors" as Krejdom.

**Comment by encukou** [comment]
I agree to license the code (not content) with the MIT license, with "naucse.python.cz contributors" as `<COPYRIGHT HOLDER>`.

**Comment by frenzymadness** [comment]
I agree to license the code (not content) with the MIT license with "naucse.python.cz contributors" as FrenzyMadness.

**Comment by hroncok** [comment]
(Sorry for the confusion with the `<COPYRIGHT HOLDER>`).

**Comment by hroncok** [comment]
Agreed.
