### ISSUE TITLE
Ugly {{ static('...') }}

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#93]
Currently, we use Jinja2 to render some lessons written in Markdown and Jupyter Notebook. To link to the static files, the `static()` macro/template filter is used. That makes the renders on GitHub and local Jupyter Notebook unusable:

![static-md-pic-gh](https://cloud.githubusercontent.com/assets/2401856/24814324/7dffa354-1bd1-11e7-9bac-98cb0b7ecc89.png)

![static-md-gh](https://cloud.githubusercontent.com/assets/2401856/24814325/7e008350-1bd1-11e7-8d59-8192edffca6f.png)

![static-ipyn-gh](https://cloud.githubusercontent.com/assets/2401856/24814326/7e032b00-1bd1-11e7-86fc-b72ff1593978.png)

This is especially bad if we want to encourage local evaluation of the Jupyter notebooks, or if we want to evaluate them automatically in the future. Could we get rid of that? Maybe keep the reference like this:

```markdown
[foo](static/bar.whatnot)
```

and making sure it works by customizing our markdown conversion to replace all `scr`s, and `href`s in the form of `static/...` into the `static()` call after the conversion (or all `[]` and `![]`targets before the conversion if that's simpler)?

**Comment by encukou** [comment]
+1
Please go ahead. Making the checkout work in Notebook would definitely be great.

**Comment by hroncok** [comment]
Hmm. Changing the content of the links is quite simple, all I have to do is to add methods `link()` and `image()` to the `Renderer`. The tricky part is that I cannot just call `nauce.routes.static()` because what's called in the lesson's template is in fact `url_for('lesson_static', lesson=lesson, path=path)`. So I would need to know the `lesson` in a thing that's supposed to take in just markdown and return HTML. I can think of several ways how to do this pretty ugly, but no way to do it right.

**Comment by hroncok** [comment]
First obvious ugly solution idea: pass the context down from `naucse.models.Page.render_html()` to `naucse.markdown_util.convert_markdown()` to `naucse.markdown_util.Renderer`. Also pass it trough `naucse.notebook_util.convert_notebook()` and `naucse.notebook_util.NaucseHTMLExporter` to pass it to `convert_markdown()`. Why it is ugly? The conversion now needs to care about context.

**Comment by hroncok** [comment]
Second obvious ugly solution idea: replace the link with Jinja2 markup (`{{ static('...') }}`) and let Jinja2 care about the context. Why it is ugly? It will only work if the document is Jinja2 enabled. We would need to know if it is (back to the problem of the first solution) or just do it and hope it is enabled (producing weird broken links otherwise is someone used a `static/...` link without enabling Jinja2 on the document). Or we would need to enable Jinja2 for all md and ipynb documents. Even if we do that, this feels hacky to me.

**Comment by encukou** [comment]
I don't think you can reliably apply Jinja after Markdown. If Mistune did preserve the Jinja tags, I'd call that behavior an implementation detail.
Two Jinja passes won't work at all. You'd need to double-escape `{% raw %}` blocks for starters, and I fear it'd just go worse from there.

Passing a context to the conversion might come in handy later, though. That's what I'd look into.
