### ISSUE TITLE
Ugly admonitions syntax

### ISSUE THREAD

**Issue by encukou** [pyvec/naucse.python.cz#97]
Naucse now uses this syntax for admonitions (notes, warnings, etc.):
```plain
!!! note ""
    Text of the note
```

This comes from [a python-markdown extension](https://pythonhosted.org/Markdown/extensions/admonition.html), which is no longer used; naucse has a custom extension for them.
Sadly, the Commonmark standard has no syntax for admonitions.
However, in discussions around Markdown and admonitions, many people are suggesting something based on blockquotes. The advantage of that is that admonitions could render relatively nicely even without the extension, e.g. on Github.

```markdown
> [note] 
> The text goes here.
```

> [note] The text goes here.

(The start text could be different, e.g. `> !note:`)

**Comment by mikicz** [comment]
I'm working on this, the syntax will be 

```
> [note] Title
> Text
>  
> Another line of text
```

Please assign the ticket to me, @encukou
